# Generated by Django 3.2 on 2023-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230830_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='titles', to='reviews.Genre', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Category slug'),
        ),
    ]
